# General
MAP_RESOLUTION = (1527, 206)


# Heatmap
HEATMAP_CUTOFF = 128

HEATMAP_BRUSH_MINSIZE = 10
HEATMAP_BRUSH_MAXSIZE = 70
HEATMAP_RESOLUTION = (300, 40)


# Network
ARROW_MAX_COLOR = 11

ARROW_MIN_SIZE = 5
ARROW_MAX_SIZE = 50
ARROW_SIZE_SCALE_FACTOR = 0.8